### ISSUE TITLE
关于在onresume 与onpause中加上暂时,与继续代码

### ISSUE THREAD

**Issue by JackChen365** [oubowu/MarqueeLayoutLibrary#1]
我想你可以直接在onWindowFocuChange中自己写.包括一些绘制.一般都会这么做,这样会方便一点.

**Comment by oubowu** [comment]
其实是因为界面不可见的时候，computeScroll那里就不执行了，然后会造成你回到这个界面时，它滚动错乱了，所以我只能在界面不可见时停止它然后回来再继续执行

**Comment by JackChen365** [comment]
哦.有没有尝试过,当失去窗体焦点时,将他强制制为当前位置起始呢.我想即使是手动调用onStart()/onStop(),也是这个作用吧.否则还是会出现滚动错乱.

**Comment by oubowu** [comment]
刚刚试了，重写了MarqueeLayout的onWindowFocusChanged方法，在这里做了暂停和恢复的处理，可行
