### ISSUE TITLE
无法动态添加多次，无法刷新

### ISSUE THREAD

**Issue by foreverxiongtao** [oubowu/MarqueeLayoutLibrary#2]
你这个貌似第一次动态添加到布局中可以，但是第二次动态添加进去后就无法进行滚动，也就是无法刷新

**Comment by oubowu** [comment]
因为项目需求较简单没有考虑动态这个，这个问题可以解决，请等待一阵，最近有点忙

**Comment by oubowu** [comment]
可以了，已经实现了动态添加删除功能，不过貌似还是有点问题
