### ISSUE TITLE
运用在viewpager，切换页面之后就无法显示

### ISSUE THREAD

**Issue by tanxinye** [oubowu/MarqueeLayoutLibrary#3]
当MarqueeLayout为viewpager其中一页时，切换页面就无法显示了

**Comment by oubowu** [comment]
还有这需求，我有时间看下，多谢关注

**Comment by oubowu** [comment]
刚刚试验了下，问题出在PagerAdapter的 destroyItem方法，如果我是这样移除view： container.removeView((View) object)，则在重新instantiateItem的时候，MarqueeLayout初始化onMeasure方法测量的是正确的；而如果这样移除 container.removeViewAt(position)，重新instantiateItem的时候，MarqueeLayout初始化onMeasure方法后拿到的宽高为0，所以就不显示了.......
这个我真的不知道啥原理，你先试下container.removeView((View) object)这个看下效果咋样？
