### ISSUE TITLE
可否加个点击事件？

### ISSUE THREAD

**Issue by xmy1231** [oubowu/MarqueeLayoutLibrary#4]

**Comment by oubowu** [comment]
可以，其实你类型recyclerview自己自定义点击监听就可以，你要的话，我加上吧

**Comment by oubowu** [comment]
已经加上，参考 72-77行https://github.com/oubowu/MarqueeLayoutLibrary/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Foushangfeng%2Fmarqueelayoutlibrary%2FMainActivity.java
