### ISSUE TITLE
内边距可以完全去掉吗？

### ISSUE THREAD

**Issue by tangbrrr** [oubowu/MarqueeLayoutLibrary#7]
子Item距离父容器自带上下左右四个间距，如何去除？

**Comment by oubowu** [comment]
布局设了padding啊 你看下示例item_simple_image和item_simple_text的xml

**Comment by tangbrrr** [comment]
恩，我把item布局里的padding删除了没生效。然后在代码中setPadding(0,0,0,0)之后生效了。
